version: '3.8'

services:
  chrome:
    image: selenium/chrome:latest
    ports:
      - "5900:5900"
    volumes:
      - ./results:/results
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    networks:
      - selenium-grid

  firefox:
    image: selenium/firefox:latest
    ports:
      - "5901:5900"
    volumes:
      - ./results:/results
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    networks:
      - selenium-grid

  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - selenium-grid

networks:
  selenium-grid:
